In [1]:
using CSV, FileIO

In [2]:
data = load("../data/impvol_data.jld2")

Dict{String,Any} with 10 entries:
  "import_shares"             => [0.0 7.85e-7 … 0.000689 0.0004425; 7.42e-5 0.0…
  "pwt"                       => [0.824111 0.620073 … 0.747101 1.0]…
  "va"                        => [3271.5 1407.45 … 4209.16 41311.0]…
  "p_sectoral_data"           => [33.0109 64.7924 … 16.8926 36.7882]…
  "io_values"                 => [2.49202e5 2423.0 … 6491.5 0.0; 4183.8 56086.1…
  "total_output"              => [2.00728e6 8.11942e5 … 1.74308e6 66853.4]…
  "intermediate_input_shares" => [0.973154 0.0268455 … 0.528231 0.294862]…
  "trade_balance"             => [1184.95 -1239.14 … -406.84 1074.1]…
  "output_shares"             => [0.967079 0.032921 … 0.521898 0.318506]…
  "beta"                      => [0.230777 0.441 … 0.297884 0.370242]…

In [3]:
country_names = CSV.read("../experiments/baseline/output_table.csv")[:country_names]

25-element Array{Union{Missings.Missing, String},1}:
 "Australia"             
 "Austria"               
 "Belgium and Luxembourg"
 "Canada"                
 "China"                 
 "Colombia"              
 "Denmark"               
 "Finland"               
 "France"                
 "Germany"               
 "Greece"                
 "India"                 
 "Ireland"               
 "Italy"                 
 "Japan"                 
 "Mexico"                
 "Netherlands"           
 "Norway"                
 "Portugal"              
 "ROW"                   
 "South Korea"           
 "Spain"                 
 "Sweden"                
 "United Kingdom"        
 "United States"         

In [4]:
function US_price_index(data, experiment)
    p_sectoral = data["p_sectoral_data"][1,end,:,:]
    parameters = load("../experiments/$experiment/common_parameters.jld2")["parameters"]
    nu = parameters[:nu_njt][1,1,:,:]
    sigma = parameters[:sigma]
    return sum(nu .* p_sectoral .^ (1-sigma), 1) .^ (1/(1-sigma))
end

US_price_index (generic function with 1 method)

In [5]:
cpi = US_price_index(data, "baseline")

1×36 Array{Float64,2}:
 35.4369  38.2792  42.5554  46.6403  …  101.635  106.828  112.764  121.02

In [6]:
# to conform with data structures
us_cpi = reshape(cpi[end,:] ./ cpi[end,1], (1,1,1,36))

1×1×1×36 Array{Float64,4}:
[:, :, 1, 1] =
 1.0

[:, :, 1, 2] =
 1.08021

[:, :, 1, 3] =
 1.20088

...

[:, :, 1, 34] =
 3.0146

[:, :, 1, 35] =
 3.18211

[:, :, 1, 36] =
 3.41508

In [7]:
dollar_price_index = data["pwt"] .* us_cpi

1×25×1×36 Array{Float64,4}:
[:, :, 1, 1] =
 0.824111  0.620073  0.816447  1.0138  …  0.469671  1.04781  0.747101  1.0

[:, :, 1, 2] =
 1.13936  0.795024  0.995663  1.11022  …  0.59099  1.25141  0.825284  1.08021

[:, :, 1, 3] =
 1.52996  0.933944  1.14979  1.28988  …  0.71763  1.38363  0.944267  1.20088

...

[:, :, 1, 34] =
 2.9687  3.10978  3.24485  2.87797  …  2.75216  3.65456  3.34459  3.0146

[:, :, 1, 35] =
 3.09307  3.27387  3.43026  3.21288  …  2.95291  3.85804  3.56349  3.18211

[:, :, 1, 36] =
 3.69163  3.80254  3.96708  3.60814  …  3.46297  4.4728  4.11468  3.41508

In [8]:
real_GDP_data = sum(data["va"], 3) ./ dollar_price_index

1×25×1×36 Array{Float64,4}:
[:, :, 1, 1] =
 64455.1  32858.7  40728.9  96150.9  …  37030.6  1.99307e5  1.12031e6

[:, :, 1, 2] =
 65982.8  31871.0  43135.0  1.0269e5  …  37735.3  2.06264e5  1.16062e6

[:, :, 1, 3] =
 62482.1  32631.5  43912.9  1.08415e5  …  39417.2  1.97532e5  1.13239e6

...

[:, :, 1, 34] =
 2.07894e5  88385.4  1.14103e5  3.67082e5  …  88693.0  6.07157e5  3.88509e6

[:, :, 1, 35] =
 2.14854e5  89878.8  114863.0  371576.0  …  90640.8  6.10731e5  3.89961e6

[:, :, 1, 36] =
 2.14192e5  89132.5  1.14673e5  3.69017e5  …  90536.3  6.08616e5  3.80577e6

In [9]:
include("../output.jl")
using ImpvolOutput
parameters = load("../experiments/baseline/common_parameters.jld2")["parameters"]


Dict{Symbol,Any} with 45 entries:
  :S_nt                     => [0.0 0.0 … 0.0 0.0]…
  :one_over_rho             => 0.0
  :inner_tolerance          => 0.0002
  :S_nt_data                => [1184.95 -1239.14 … -406.84 1074.1]…
  :eta                      => 4.0
  :S                        => 101
  :sigma                    => 0.999
  :d                        => [0.991383 7.85e-7 … 0.000689 0.0004425; 7.42e-5 …
  :adjustment_tolerance     => 0.0004
  :middle_step_size         => 0.449329
  :A_njs                    => Array{Float64,4}[[1466.01 503.068 … 1568.37 7165…
  :gamma_jk                 => [0.17112 0.273944 … 0.0195213 0.0108426; 0.04826…
  :p_sectoral               => [1.26077 2.37256 … 1.79398 1.0]…
  :B_j                      => [5.5087]…
  :max_iter_adjustment      => 100
  :w_njt                    => [53118.2 20374.8 … 1.48903e5 1.12031e6]…
  :global_sectoral_shock    => [7.02105e-15]…
  :country_shock_njs        => Array{Float64,4}[[-2.70733e-16 -4.55558e-16 … 7.…
  :idi

In [10]:
function volatility(scenario)
    results = load("../experiments/$scenario/results.jld2")["results"]
    real_GDP_model = sum(ImpvolOutput.make_series(results, :real_GDP), 3)
    return ImpvolOutput.calculate_volatilities(real_GDP_model, parameters, true)[:].^0.5
end

volatility (generic function with 1 method)

In [11]:
data_volatility = ImpvolOutput.calculate_volatilities(real_GDP_data, parameters, true)[:].^0.5
model_volatility = volatility("baseline/actual")
CES05_volatility = volatility("CES0.5/actual")
[data_volatility model_volatility CES05_volatility]

25×3 Array{Float64,2}:
 0.0303417  0.0300324  0.0300731
 0.0142093  0.023187   0.0200961
 0.0178478  0.0319788  0.0282974
 0.0139503  0.0243677  0.0207991
 0.0762514  0.0789922  0.0782933
 0.0293101  0.0331822  0.0377017
 0.0168866  0.0210463  0.0191225
 0.0209671  0.0248714  0.0255093
 0.0136236  0.0139932  0.0143874
 0.01504    0.0155931  0.0153524
 0.0190854  0.0172922  0.025762 
 0.0307193  0.0319376  0.0359316
 0.0251652  0.0323663  0.0332292
 0.0138399  0.0137948  0.0148073
 0.0168999  0.0172045  0.0166729
 0.0275213  0.0324076  0.0329034
 0.0116397  0.0183437  0.0164287
 0.0253615  0.0289954  0.0257151
 0.0338734  0.0395185  0.0370693
 0.0401589  0.0406178  0.0409356
 0.0315266  0.0292037  0.0318188
 0.0137769  0.0155436  0.0156149
 0.0153384  0.0186054  0.0177927
 0.0149432  0.0153756  0.0148609
 0.0160794  0.0161791  0.0151603

In [12]:
function regression(x, y)
    X = [ones(length(x)) x]
    beta = X \ y
    R2 = var(X * beta) / var(y)
    return (beta, R2, X*beta)
end

regression (generic function with 1 method)

In [20]:
using Plots
import GR
fm = x->repr(round(x, 3))


(::#17) (generic function with 1 method)

In [21]:
function plot_model_data(scenario, fname)
    model_volatility = volatility(scenario)
    beta, R2, fitted = regression(data_volatility, model_volatility)
    if beta[2]>0
        label = "y = $(fm(beta[1]))+$(fm(beta[2]))x\nR2 = $(fm(R2)), rho = $(fm(R2^.5))"
    else
        label = "y = $(fm(beta[1]))-$(fm(-beta[2]))x\nR2 = $(fm(R2)), rho = $(fm(-R2^.5))"
    end
    plot(data_volatility, fitted, label=label, xlabel="Data volatility (standard deviation)", size=(800,500))
    scatter!(data_volatility, model_volatility, label="", ylabel="Model volatility (standard deviation)")
    x = 0.002
    for i=1:length(data_volatility)
        annotate!(data_volatility[i], model_volatility[i]+x, text(country_names[i], :black, :center, 10))
    end
    savefig(fname)
end

plot_model_data (generic function with 1 method)

In [22]:
plot_model_data("baseline/actual", "../output/Figure2.pdf")
plot_model_data("CES0.5/actual", "../output/CES0.5-model-data.pdf")
model_volatility = volatility("baseline/actual") 

25-element Array{Float64,1}:
 0.0300324
 0.023187 
 0.0319788
 0.0243677
 0.0789922
 0.0331822
 0.0210463
 0.0248714
 0.0139932
 0.0155931
 0.0172922
 0.0319376
 0.0323663
 0.0137948
 0.0172045
 0.0324076
 0.0183437
 0.0289954
 0.0395185
 0.0406178
 0.0292037
 0.0155436
 0.0186054
 0.0153756
 0.0161791

In [23]:
# without china
beta, R2 = regression([data_volatility[1:4]; data_volatility[6:end]], [model_volatility[1:4]; model_volatility[6:end]])
correlation = R2^.5

0.8785749349078213

In [24]:
# correlation of variances
beta, R2 = regression(data_volatility.^2, model_volatility.^2)
correlation = R2^.5

0.9867716811859206

In [25]:
# correlation of variances
# without china
beta, R2 = regression([data_volatility[1:4]; data_volatility[6:end]].^2, [model_volatility[1:4]; model_volatility[6:end]].^2)
correlation = R2^.5

0.89200181820561

In [27]:
plot_model_data("CES1.5/actual", "../output/CES2-model-data.pdf")
